trigger:
  branches:
    include:
      - main

pool:
  name: Default

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 
      echo "funciono creo"
      #sudo apt-get install wget -y 
      #sudo wget https://github.com/AlejandroPC122/Pruebas.git
