trigger:
  branches:
    include:
      - main

pool:
  name: Default
steps:
- task: AzureStaticWebApp@0
  inputs:
    skip_app_build: true
    skip_api_build: true
    is_static_export: true
    verbose: true

- task: IISWebAppDeploymentOnMachineGroup@0
  inputs:
    WebSiteName: 'pruebas'
    Package: '$(System.DefaultWorkingDirectory)\**\*.zip'
