trigger:
  branches:
    include:
      - main

pool:
  name: vm1web

steps:
- task: AzureCLI@2
  inputs:
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "funciono creo"
      #sudo apt-get install wget -y 
      #sudo wget https://github.com/AlejandroPC122/Pruebas.git
