trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      sudo apt-get install wget -y 
      sudo wget https://github.com/AlejandroPC122/Pruebas.git
      scp */esteno.md myadmin@20.101.139.39:/home/myadmin/
